using System;
using System.Collections;
using System.Collections.Generic;
using DG.Tweening;
using UnityEngine;
using UnityEngine.SceneManagement;

public class GameManager : MonoBehaviour
{
    public static GameManager Instance { get; private set; }
    public Collider2D floorCollider;
    public CanvasGroup finishPanel;
    public CanvasGroup startPanel;
    public GameObject explosionVfx;

    private List<Draggable2D> itemsList;
    private Collider2D[] allColliders;
    private bool finished = false;
    
    private void Awake()
    {
        // –ï—Å–ª–∏ —ç–∫–∑–µ–º–ø–ª—è—Ä —É–∂–µ —Å—É—â–µ—Å—Ç–≤—É–µ—Ç ‚Äî —É–Ω–∏—á—Ç–æ–∂–∞–µ–º –¥—É–±–ª–∏–∫–∞—Ç
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        // –ù–∞–∑–Ω–∞—á–∞–µ–º —Ç–µ–∫—É—â–∏–π —ç–∫–∑–µ–º–ø–ª—è—Ä
        Instance = this;

        // üîπ –°–æ—Ö—Ä–∞–Ω—è–µ–º –æ–±—ä–µ–∫—Ç –ø—Ä–∏ —Å–º–µ–Ω–µ —Å—Ü–µ–Ω
        //DontDestroyOnLoad(gameObject);
        
        
        int layerToFind = LayerMask.NameToLayer("Item"); // –∏–º—è —Å–ª–æ—è

        Draggable2D[] allObjects = FindObjectsOfType<Draggable2D>();
        itemsList = new List<Draggable2D>();

        foreach (Draggable2D obj in allObjects)
        {
            if (obj.gameObject.layer == layerToFind)
                itemsList.Add(obj);
        }
        
        allColliders =  FindObjectsOfType<Collider2D>();

        Debug.Log($"–ù–∞–π–¥–µ–Ω–æ {itemsList.Count} –æ–±—ä–µ–∫—Ç–æ–≤ –Ω–∞ —Å–ª–æ–µ {LayerMask.LayerToName(layerToFind)}");
        
        finished = false;
        finishPanel.gameObject.SetActive(false);

        startPanel.gameObject.SetActive(true);
        startPanel.DOFade(1f, 0.4f);
    }

    public void Update()
    {
        if (finished == false)
        {
            finished = true;
            foreach (var item in itemsList)
            {
                finished = item.CheckStable() && finished;
            }

            if (finished)
            {
                ShowFinishScreen();
            }
        }
    }

    public Collider2D GetFloorCollider()
    {
        return floorCollider;
    }

    public Collider2D[] GetAllColliders()
    {
        return allColliders;
    }

    private void ShowFinishScreen()
    {
        finishPanel.gameObject.SetActive(true);
        finishPanel.alpha = 0f;
        finishPanel.DOFade(1f,0.4f);
    }

    public void StartGame()
    {
        startPanel.DOFade(0f, 0.4f).OnComplete(() =>
        {
            startPanel.gameObject.SetActive(false);
        });
    }

    public void RestartScene()
    {
        Scene currentScene = SceneManager.GetActiveScene();
        SceneManager.LoadScene(currentScene.buildIndex);
    }

    public void SpawnExplosion(Vector3 position)
    {
        Instantiate(explosionVfx, position, Quaternion.identity);
    }
}
